build:
  image: default-bionic
  environment:
    php: 8.1.2
    pecl_extensions:
      - ds
      - pcov
  nodes:
    analysis:
filter:
  excluded_paths:
    - 'app/*'
    - 'docs/*'
    - 'tests/*'
    - 'features/*'
checks:
  php: true
