build:
  image: default-bionic
  environment:
    php: 8.1.2
  nodes:
    analysis:
      dependencies:
        before:
          - pecl install pcov ds
          - pecl enable pcov ds
      project_setup:
        override:
          - php-scrutinizer-run
filter:
  excluded_paths:
    - 'app/*'
    - 'docs/*'
    - 'tests/*'
    - 'features/*'
checks:
  php: true
