build:
  image: default-bionic
  nodes:
    analysis:
      environment:
        php:
          version: 8.1.2
          pecl_extensions:
            - ds
            - pcov
        variables:
          APP_BUILD_DIR: build
          APP_CACHE_DIR: build/cache
          APP_LOG_DIR: build/logs
      dependencies:
        before:
          - /usr/local/bin/composer self-update
          - mkdir -p "${APP_BUILD_DIR}"
filter:
  excluded_paths:
    - 'app/*'
    - 'docs/*'
    - 'tests/*'
    - 'features/*'
checks:
  php: true
