build:
  image: default-bionic
  environment:
    php: 8.1.2
  nodes:
    analysis:
      dependencies:
        before:
          - pecl install pcov ds
          - pecl enable pcov ds
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
            command: phpcs-run
          - js-scrutinizer-run
    tests: true
filter:
  excluded_paths:
    - 'app/*'
    - 'docs/*'
    - 'tests/*'
    - 'features/*'
checks:
  php: true
  javascript: true
coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true
