build:
  image: default-bionic
  environment:
    php: 8.1.2
  nodes:
    analysis:
      dependencies:
        before:
          - pecl install pcov ds
          - pecl enable pcov ds
filter:
  excluded_paths:
    - 'app/*'
    - 'docs/*'
    - 'tests/*'
    - 'features/*'
checks:
  php: true
