build:
  image: default-bionic
  nodes:
    analysis:
      environment:
        php:
          version: 8.1.2
          pecl_extensions:
            - ds
            - pcov
      tests:
        override:
          - php-scrutinizer-run
filter:
  excluded_paths:
    - 'app/*'
    - 'docs/*'
    - 'tests/*'
    - 'features/*'
checks:
  php: true
