tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "snyk/tap"
tap "symfony-cli/tap"

brew "php"
brew "composer"
cask "docker"
brew "gh"
brew "git"
brew "make"
brew "snyk/tap/snyk"
brew "symfony-cli/tap/symfony-cli"
