---
version: '3.7'

services:
  bundle:
    build:
      context: ./
      dockerfile: docker/services/bundle/Dockerfile
    environment:
      APP_CODE_DIR: "${APP_CODE_DIR?err}"
      APP_BUILD_DIR: "${APP_BUILD_DIR}"
      APP_CACHE_DIR: '/cache'
      APP_LOG_DIR: '/cushon/build/logs/symfony'
      APP_ENV: "${APP_ENV}"
    restart: unless-stopped
    volumes:
      - ./:/cushon
    networks:
      - app
  nginx:
    build:
      context: docker/services/nginx
      dockerfile: Dockerfile
    environment:
      APP_CODE_DIR: "${APP_CODE_DIR?err}"
      NGINX_PORT: "${NGINX_PORT:-8080}"
    networks:
      - app
    restart: unless-stopped
    ports:
      - "${HOST_NGINX_PORT:?err}:${NGINX_PORT:-8080}"
  blackfire:
    image: blackfire/blackfire:2
    ports: [ "8307" ]
    environment:
      # Exposes BLACKFIRE_* environment variables from the host
      BLACKFIRE_SERVER_ID: ~
      BLACKFIRE_SERVER_TOKEN: ~
      BLACKFIRE_CLIENT_ID: ~
      BLACKFIRE_CLIENT_TOKEN: ~
networks:
  app:
