---
services:
  App\ApplicationHealth\DependencyCheck\NullDependencyCheck:
    arguments:
      $name: 'Null dependency'
      $health: true
      $info: 'Some info about the fake dependency'
    tags:
      - 'cushon_health.dependency_check'
