---
services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Disable the example Null Dependency Check in test
  App\ApplicationHealth\DependencyCheck\NullDepdencyCheck:
    autowire: false
    autoconfigure: false

  Cushon\HealthBundle\Console\Command\CheckHealth:
    public: true

  Cushon\HealthBundle\QueryBus\MessengerHealthQueryBus:
    public: true

  Symfony\Component\HttpKernel\KernelInterface: '@kernel'

  app.dependency_check1:
    synthetic: true
    public: true
    tags:
      - 'cushon_health.dependency_check'
        
  app.dependency_check2:
    synthetic: true
    public: true
    tags:
      - 'cushon_health.dependency_check'

  Tests\Behat\:
    resource: '%cushon_health.bundle_path%/../tests/behat/src/*'
