# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  secret: '%env(APP_SECRET)%'
  #csrf_protection: true
  http_method_override: false

  # Enables session support. Note that the session will ONLY be started if you read or write from it.
  # Remove or comment this section to explicitly disable session support.
  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax
    storage_factory_id: session.storage.factory.native

  #esi: true
  #fragments: true
  php_errors:
    log: true
when@prod: &prod
  framework:
    http_client:
      # https://www.random.org/integers/?num=10&min=1&max=6&col=1&base=10&format=plain&rnd=new
      scoped_clients:
        random.client:
          base_uri: 'https://www.random.org'

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
