name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pecl extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: intl, opcache, pcov, ds

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install dependencies
        run: composer install

      - name: Run test suite
        run: composer test
        env:
          APP_BUILD_DIR: ${{ runner.temp }}
          APP_CACHE_DIR: ${{ runner.temp }}/cache
          APP_LOG_DIR: ${{ runner.temp }}/logs
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
