name: PHP Test suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pecl extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: intl, opcache, pcov, ds
      - name: Make tempoary build dir
        run: mkdir -p build

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install dependencies
        run: composer install

      - name: Run test suite
        run: composer test
        env:
          APP_BUILD_DIR: ${{ runner.temp }}
          APP_CACHE_DIR: ${{ runner.temp }}/cache
          APP_LOG_DIR: ${{ runner.temp }}/logs
          COVERAGE_DIR: ${{ runner.temp }}/coverage
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
      - uses: codecov/codecov-action@v2
        with:
          directory: ${{ runner.temp }}/coverage
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
          parallel: true
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: ${COVERAGE_DIR}
          github-token: ${{ secrets.github_token }}
          flag-name: run-${{ matrix.test_number }}
          parallel: true
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
